"""describe the change

Revision ID: 2b40dd5d5fa3
Revises: 42b64ad9c328
Create Date: 2026-07-14 15:38:49.733451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b40dd5d5fa3'
down_revision: Union[str, Sequence[str], None] = '42b64ad9c328'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        "CREATE SCHEMA IF NOT EXISTS projects"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
