"""create project officer and member tables

Revision ID: 42b64ad9c328
Revises: 
Create Date: 2026-07-14 15:29:53.456270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42b64ad9c328'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('officer_details',
    sa.Column('officer_id', sa.String(length=150), nullable=False),
    sa.Column('officer_uuid', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('officer_name', sa.String(length=150), nullable=False),
    sa.Column('officer_designation', sa.String(length=150), nullable=True),
    sa.Column('officer_email', sa.String(length=254), nullable=True),
    sa.Column('officer_status', sa.Boolean(), nullable=False),
    sa.Column('officer_created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('officer_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(trim(officer_id)) >= 2', name='ck_officer_id_min_length'),
    sa.CheckConstraint('char_length(trim(officer_name)) >= 2', name='ck_officer_name_min_length'),
    sa.CheckConstraint('department_id > 0', name='ck_officer_department_id_positive'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.departments.department_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('officer_id'),
    schema='projects'
    )
    op.create_index(op.f('ix_projects_officer_details_department_id'), 'officer_details', ['department_id'], unique=False, schema='projects')
    op.create_index(op.f('ix_projects_officer_details_officer_email'), 'officer_details', ['officer_email'], unique=True, schema='projects')
    op.create_index(op.f('ix_projects_officer_details_officer_name'), 'officer_details', ['officer_name'], unique=False, schema='projects')
    op.create_index(op.f('ix_projects_officer_details_officer_status'), 'officer_details', ['officer_status'], unique=False, schema='projects')
    op.create_index(op.f('ix_projects_officer_details_officer_uuid'), 'officer_details', ['officer_uuid'], unique=True, schema='projects')
    op.create_table('projects',
    sa.Column('project_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_uuid', sa.UUID(), nullable=False),
    sa.Column('project_name', sa.String(length=200), nullable=False),
    sa.Column('project_budget', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('project_status', sa.Enum('PLANNED', 'IN_PROGRESS', 'ON_HOLD', 'COMPLETED', 'CANCELLED', name='project_status_values', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('project_start_date', sa.Date(), nullable=True),
    sa.Column('project_expected_end_date', sa.Date(), nullable=True),
    sa.Column('project_description', sa.Text(), nullable=True),
    sa.Column('officer_id', sa.String(length=150), nullable=False),
    sa.Column('project_created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('project_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('\n            project_expected_end_date IS NULL\n            OR project_start_date IS NULL\n            OR project_expected_end_date >= project_start_date\n            ', name='ck_project_end_after_start'),
    sa.CheckConstraint('char_length(trim(project_name)) >= 2', name='ck_project_name_min_length'),
    sa.CheckConstraint('department_id > 0', name='ck_project_department_id_positive'),
    sa.CheckConstraint('project_budget >= 0', name='ck_project_budget_non_negative'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.departments.department_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['officer_id'], ['projects.officer_details.officer_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id'),
    schema='projects'
    )
    op.create_index(op.f('ix_projects_projects_department_id'), 'projects', ['department_id'], unique=False, schema='projects')
    op.create_index(op.f('ix_projects_projects_officer_id'), 'projects', ['officer_id'], unique=False, schema='projects')
    op.create_index(op.f('ix_projects_projects_project_name'), 'projects', ['project_name'], unique=False, schema='projects')
    op.create_index(op.f('ix_projects_projects_project_status'), 'projects', ['project_status'], unique=False, schema='projects')
    op.create_index(op.f('ix_projects_projects_project_uuid'), 'projects', ['project_uuid'], unique=True, schema='projects')
    op.create_table('project_members',
    sa.Column('member_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_uuid', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('developer_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by_id', sa.String(length=150), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('member_status', sa.Boolean(), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('developer_id > 0', name='ck_project_member_developer_id_positive'),
    sa.CheckConstraint('project_id > 0', name='ck_project_member_project_id_positive'),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['projects.officer_details.officer_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('member_id'),
    sa.UniqueConstraint('project_id', 'developer_id', name='uq_project_member_project_developer'),
    schema='projects'
    )
    op.create_index(op.f('ix_projects_project_members_assigned_by_id'), 'project_members', ['assigned_by_id'], unique=False, schema='projects')
    op.create_index(op.f('ix_projects_project_members_developer_id'), 'project_members', ['developer_id'], unique=False, schema='projects')
    op.create_index(op.f('ix_projects_project_members_member_status'), 'project_members', ['member_status'], unique=False, schema='projects')
    op.create_index(op.f('ix_projects_project_members_member_uuid'), 'project_members', ['member_uuid'], unique=True, schema='projects')
    op.create_index(op.f('ix_projects_project_members_project_id'), 'project_members', ['project_id'], unique=False, schema='projects')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_project_members_project_id'), table_name='project_members', schema='projects')
    op.drop_index(op.f('ix_projects_project_members_member_uuid'), table_name='project_members', schema='projects')
    op.drop_index(op.f('ix_projects_project_members_member_status'), table_name='project_members', schema='projects')
    op.drop_index(op.f('ix_projects_project_members_developer_id'), table_name='project_members', schema='projects')
    op.drop_index(op.f('ix_projects_project_members_assigned_by_id'), table_name='project_members', schema='projects')
    op.drop_table('project_members', schema='projects')
    op.drop_index(op.f('ix_projects_projects_project_uuid'), table_name='projects', schema='projects')
    op.drop_index(op.f('ix_projects_projects_project_status'), table_name='projects', schema='projects')
    op.drop_index(op.f('ix_projects_projects_project_name'), table_name='projects', schema='projects')
    op.drop_index(op.f('ix_projects_projects_officer_id'), table_name='projects', schema='projects')
    op.drop_index(op.f('ix_projects_projects_department_id'), table_name='projects', schema='projects')
    op.drop_table('projects', schema='projects')
    op.drop_index(op.f('ix_projects_officer_details_officer_uuid'), table_name='officer_details', schema='projects')
    op.drop_index(op.f('ix_projects_officer_details_officer_status'), table_name='officer_details', schema='projects')
    op.drop_index(op.f('ix_projects_officer_details_officer_name'), table_name='officer_details', schema='projects')
    op.drop_index(op.f('ix_projects_officer_details_officer_email'), table_name='officer_details', schema='projects')
    op.drop_index(op.f('ix_projects_officer_details_department_id'), table_name='officer_details', schema='projects')
    op.drop_table('officer_details', schema='projects')
    # ### end Alembic commands ###
