"""create work order module

Revision ID: a251921d8cb9
Revises: 2b40dd5d5fa3
Create Date: 2026-07-30 15:31:14.121952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a251921d8cb9'
down_revision: Union[str, Sequence[str], None] = '2b40dd5d5fa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS work_orders")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_orders',
    sa.Column('work_order_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_order_uuid', sa.UUID(), nullable=False),
    sa.Column('work_order_number', sa.String(length=100), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('developer_id', sa.Integer(), nullable=False),
    sa.Column('officer_id', sa.String(length=150), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('monthly_salary', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('work_order_start_date', sa.Date(), nullable=False),
    sa.Column('work_order_end_date', sa.Date(), nullable=False),
    sa.Column('number_of_months', sa.Integer(), nullable=True),
    sa.Column('work_order_description', sa.Text(), nullable=True),
    sa.Column('project_name_snapshot', sa.String(length=200), nullable=False),
    sa.Column('department_name_snapshot', sa.String(length=200), nullable=False),
    sa.Column('developer_name_snapshot', sa.String(length=200), nullable=False),
    sa.Column('officer_name_snapshot', sa.String(length=200), nullable=False),
    sa.Column('work_order_status', sa.Enum('DRAFT', 'GENERATED', 'PENDING_SIGNATURE', 'SIGNED', 'CANCELLED', name='Work_Order_Status_values', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('unsigned_pdf_base64', sa.Text(), nullable=True),
    sa.Column('signed_pdf_base64', sa.Text(), nullable=True),
    sa.Column('signed_pdf_sha256', sa.String(length=64), nullable=True),
    sa.Column('signed_by_officer_id', sa.String(length=150), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('work_order_created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('work_order_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('monthly_salary >= 0', name='ck_work_order_salary_non_negetive'),
    sa.CheckConstraint('tier >= 1', name='ck_work_order_tier_positive'),
    sa.CheckConstraint('work_order_end_date >= work_order_start_date', name='ck_work_order_end_after_start'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.departments.department_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['officer_id'], ['projects.officer_details.officer_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.projects.project_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['signed_by_officer_id'], ['projects.officer_details.officer_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('work_order_id'),
    sa.UniqueConstraint('work_order_number', name='uq_work_order_number'),
    schema='work_orders'
    )
    op.create_index(op.f('ix_work_orders_work_orders_department_id'), 'work_orders', ['department_id'], unique=False, schema='work_orders')
    op.create_index(op.f('ix_work_orders_work_orders_developer_id'), 'work_orders', ['developer_id'], unique=False, schema='work_orders')
    op.create_index(op.f('ix_work_orders_work_orders_officer_id'), 'work_orders', ['officer_id'], unique=False, schema='work_orders')
    op.create_index(op.f('ix_work_orders_work_orders_project_id'), 'work_orders', ['project_id'], unique=False, schema='work_orders')
    op.create_index(op.f('ix_work_orders_work_orders_signed_by_officer_id'), 'work_orders', ['signed_by_officer_id'], unique=False, schema='work_orders')
    op.create_index(op.f('ix_work_orders_work_orders_tier'), 'work_orders', ['tier'], unique=False, schema='work_orders')
    op.create_index(op.f('ix_work_orders_work_orders_work_order_number'), 'work_orders', ['work_order_number'], unique=True, schema='work_orders')
    op.create_index(op.f('ix_work_orders_work_orders_work_order_status'), 'work_orders', ['work_order_status'], unique=False, schema='work_orders')
    op.create_index(op.f('ix_work_orders_work_orders_work_order_uuid'), 'work_orders', ['work_order_uuid'], unique=True, schema='work_orders')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_orders_work_orders_work_order_uuid'), table_name='work_orders', schema='work_orders')
    op.drop_index(op.f('ix_work_orders_work_orders_work_order_status'), table_name='work_orders', schema='work_orders')
    op.drop_index(op.f('ix_work_orders_work_orders_work_order_number'), table_name='work_orders', schema='work_orders')
    op.drop_index(op.f('ix_work_orders_work_orders_tier'), table_name='work_orders', schema='work_orders')
    op.drop_index(op.f('ix_work_orders_work_orders_signed_by_officer_id'), table_name='work_orders', schema='work_orders')
    op.drop_index(op.f('ix_work_orders_work_orders_project_id'), table_name='work_orders', schema='work_orders')
    op.drop_index(op.f('ix_work_orders_work_orders_officer_id'), table_name='work_orders', schema='work_orders')
    op.drop_index(op.f('ix_work_orders_work_orders_developer_id'), table_name='work_orders', schema='work_orders')
    op.drop_index(op.f('ix_work_orders_work_orders_department_id'), table_name='work_orders', schema='work_orders')
    op.drop_table('work_orders', schema='work_orders')
    # ### end Alembic commands ###
    op.execute("DROP SCHEMA IF EXISTS work_orders")
